services:
  - type: web
    name: fitness-assistant
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python agent.py download-files
    startCommand: python agent.py dev
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8080"
