services:
  - type: web
    name: fitness-assistant
    env: python
    plan: starter  # Use paid plan for more memory
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: python agent.py start
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8080"
