services:
  - type: web
    name: androfitai-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python agent.py download-files
    startCommand: python agent.py start
    memory: 1024
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false